[package]
name = "bevy_startup_tree"
version = "0.2.0"
edition = "2021"
description = "A bevy extension for inserting  startup system dependency graphs into the app"
documentation = "https://docs.rs/bevy_startup_tree"
keywords = ["bevy", "game", "gamedev", "tree", "utility"]
license = "MIT OR Apache-2.0"
exclude = ["examples/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["macros/*", "examples/*"]

[dependencies]
bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
bevy_startup_tree_macros = { version = "0.2.0", path = "./macros/bevy_startup_tree_macros" }
itertools = "0.11"
rand = "0.8.5"

[dev-dependencies]
bevy = { version = "0.10.1", default-features = false }
delegate = "0.9.0"
